/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import static Interfaz.Carnet.jTextField1;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Aprendiz extends Persona {
    
    private String CodigoAprendiz;
    
    public String getCodigo() {
        return CodigoAprendiz;
    }

    public void setCodigo(String Codigo) {
        
        this.CodigoAprendiz = Codigo;
    }

    public JTextField getjTextFieldCodigo() {
        return jTextFieldCodigo;
    }

    public void setjTextFieldCodigo(JTextField jTextFieldCodigo) {
        this.jTextFieldCodigo = jTextFieldCodigo;
    }

    /**
     * Creates new form Aprendiz
     */
    public Aprendiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAtrass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bG = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jButtonEnviar = new javax.swing.JButton();
        jTextFieldCodigo = new javax.swing.JTextField();
        MenuColor = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(698, 750));
        getContentPane().setLayout(null);

        jButtonAtrass.setBackground(new java.awt.Color(102, 255, 102));
        jButtonAtrass.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jButtonAtrass.setText("ATRAS");
        jButtonAtrass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrassActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtrass);
        jButtonAtrass.setBounds(0, 0, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo3.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 900));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 900));
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, -10, 0, 0);

        bG.setBackground(new java.awt.Color(255, 255, 255));
        bG.setMaximumSize(new java.awt.Dimension(653, 642));
        bG.setMinimumSize(new java.awt.Dimension(653, 642));
        bG.setPreferredSize(new java.awt.Dimension(653, 642));
        bG.setLayout(null);

        jLabelNombre.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabelNombre.setText("NOMBRE");
        bG.add(jLabelNombre);
        jLabelNombre.setBounds(50, 120, 157, 43);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextFieldNombre.setMaximumSize(new java.awt.Dimension(6, 35));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        bG.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(50, 170, 580, 43);

        jLabelApellido.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabelApellido.setText("APELLIDO");
        bG.add(jLabelApellido);
        jLabelApellido.setBounds(50, 230, 174, 43);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextFieldApellido.setMaximumSize(new java.awt.Dimension(6, 35));
        bG.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(50, 290, 580, 43);

        jLabelEdad.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabelEdad.setText("EDAD");
        bG.add(jLabelEdad);
        jLabelEdad.setBounds(50, 350, 99, 43);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextFieldEdad.setMaximumSize(new java.awt.Dimension(6, 35));
        jTextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadActionPerformed(evt);
            }
        });
        jTextFieldEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadKeyTyped(evt);
            }
        });
        bG.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(50, 410, 580, 46);

        jLabelCodigo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabelCodigo.setText("CODIGO");
        bG.add(jLabelCodigo);
        jLabelCodigo.setBounds(50, 470, 145, 43);

        jButtonEnviar.setBackground(new java.awt.Color(102, 255, 51));
        jButtonEnviar.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jButtonEnviar.setText("ENVIAR DATOS");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        bG.add(jButtonEnviar);
        jButtonEnviar.setBounds(160, 600, 370, 80);

        jTextFieldCodigo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextFieldCodigo.setMaximumSize(new java.awt.Dimension(6, 35));
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        bG.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(50, 520, 580, 50);

        MenuColor.setBackground(new java.awt.Color(255, 153, 51));
        MenuColor.setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setText("DATOS DE APRENDIZ");
        MenuColor.add(jLabelTitulo);
        jLabelTitulo.setBounds(150, 10, 490, 43);

        bG.add(MenuColor);
        MenuColor.setBounds(0, 40, 680, 60);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        bG.add(jPanel1);
        jPanel1.setBounds(0, 100, 680, 610);

        getContentPane().add(bG);
        bG.setBounds(0, 0, 680, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
                
        String nombre = jTextFieldNombre.getText();
        String apellido = jTextFieldApellido.getText();
        
        String cod = jTextFieldCodigo.getText();
        String edad = jTextFieldEdad.getText();
        
        if(nombre.equals("")){  
            JOptionPane.showMessageDialog(null,"El campo no puede estar vacío");
                        return;
        }   
        if(apellido.equals("")){  
            JOptionPane.showMessageDialog(null,"El campo no puede estar vacío");
                        return;

        }   
        if(edad.equals("")){  
            JOptionPane.showMessageDialog(null,"El campo no puede estar vacío");
                        return;

        }   
        if(cod.equals("")){  
            JOptionPane.showMessageDialog(null,"El campo no puede estar vacío");
                        return;

        }
        
        
        
        Carnet carnet = new Carnet();
        carnet.mostrarCarnet(nombre, apellido, edad, cod);
        dispose();
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonAtrassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrassActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtrassActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadActionPerformed

    private void jTextFieldEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && (car<',' || car >','))evt.consume();
    }//GEN-LAST:event_jTextFieldEdadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aprendiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aprendiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aprendiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aprendiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aprendiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuColor;
    private javax.swing.JPanel bG;
    private javax.swing.JButton jButtonAtrass;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
