/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author SENA
 */
public class Circulo extends javax.swing.JFrame {

    /**
     * Creates new form Circulo
     */
    public Circulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButtonAtrasss = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelRadioIngreso = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldRadio = new javax.swing.JTextField();
        jLabelRadioIngreso1 = new javax.swing.JLabel();
        jTextArea = new javax.swing.JTextField();
        jLabelRadioIngreso2 = new javax.swing.JLabel();
        jTextCircunferencia = new javax.swing.JTextField();
        jLabelRadioIngreso3 = new javax.swing.JLabel();
        jTextVolumen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(629, 546));
        getContentPane().setLayout(null);

        jButtonAtrasss.setBackground(new java.awt.Color(102, 255, 51));
        jButtonAtrasss.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jButtonAtrasss.setText("ATRAS");
        jButtonAtrasss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasssActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtrasss);
        jButtonAtrasss.setBounds(0, 0, 170, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabelRadioIngreso.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabelRadioIngreso.setText("Ingresar el Radio del circulo");
        jPanel1.add(jLabelRadioIngreso);
        jLabelRadioIngreso.setBounds(20, 160, 250, 30);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabelTitulo.setText("EL CIRCULO");
        jPanel1.add(jLabelTitulo);
        jLabelTitulo.setBounds(200, 60, 240, 60);

        jTextFieldRadio.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jTextFieldRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRadioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRadio);
        jTextFieldRadio.setBounds(280, 150, 270, 35);

        jLabelRadioIngreso1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabelRadioIngreso1.setText("Ingresar el Area del circulo");
        jPanel1.add(jLabelRadioIngreso1);
        jLabelRadioIngreso1.setBounds(20, 220, 250, 30);

        jTextArea.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAreaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextArea);
        jTextArea.setBounds(280, 210, 270, 35);

        jLabelRadioIngreso2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabelRadioIngreso2.setText("Ingresar la Circunferencia del circulo");
        jPanel1.add(jLabelRadioIngreso2);
        jLabelRadioIngreso2.setBounds(20, 280, 330, 22);

        jTextCircunferencia.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jTextCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCircunferenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCircunferencia);
        jTextCircunferencia.setBounds(350, 270, 240, 35);

        jLabelRadioIngreso3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabelRadioIngreso3.setText("Ingresar el Volumen del circulo");
        jPanel1.add(jLabelRadioIngreso3);
        jLabelRadioIngreso3.setBounds(20, 340, 270, 30);

        jTextVolumen.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jTextVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVolumenActionPerformed(evt);
            }
        });
        jPanel1.add(jTextVolumen);
        jTextVolumen.setBounds(300, 330, 260, 40);

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 440, 230, 51);

        jButtonLimpiar.setBackground(new java.awt.Color(204, 102, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButtonLimpiar.setText("LIMPIAR");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(360, 440, 173, 51);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 40, 630, 100);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 140, 630, 260);

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 400, 630, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRadioActionPerformed
        
    }//GEN-LAST:event_jTextFieldRadioActionPerformed

    private void jTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaActionPerformed

    private void jTextVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVolumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVolumenActionPerformed

    private void jTextCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCircunferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCircunferenciaActionPerformed

    private void jButtonAtrasssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasssActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtrasssActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double radio, area, circunferencia, volumen;
        if(jTextFieldRadio.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese el Radio del circulo");
            jTextFieldRadio.requestFocus();
        }else{
            radio=Double.parseDouble(jTextFieldRadio.getText());
            area=(2*Math.PI*radio);
            volumen=(4*Math.PI*radio);
            circunferencia=(Math.PI*radio*radio);

            jTextArea.setText(area+"");
            jTextVolumen.setText(volumen+"");
            jTextCircunferencia.setText(circunferencia+"");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldRadio.setText("");
        jTextArea.setText("");
         jTextCircunferencia.setText("");
        jTextVolumen.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Circulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Circulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtrasss;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabelRadioIngreso;
    private javax.swing.JLabel jLabelRadioIngreso1;
    private javax.swing.JLabel jLabelRadioIngreso2;
    private javax.swing.JLabel jLabelRadioIngreso3;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextArea;
    private javax.swing.JTextField jTextCircunferencia;
    private javax.swing.JTextField jTextFieldRadio;
    private javax.swing.JTextField jTextVolumen;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
