/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import javax.swing.JOptionPane;


/**
 *
 * @author SENA
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Logobg = new javax.swing.JLabel();
        NombreAct = new javax.swing.JLabel();
        FondoBg = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFileClave = new javax.swing.JPasswordField();
        jButtonIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        passUsuario = new javax.swing.JLabel();
        SeparadorUsuario = new javax.swing.JSeparator();
        SeparadorPassword = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesion");
        setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1038, 532));
        setMinimumSize(new java.awt.Dimension(1038, 532));
        setPreferredSize(new java.awt.Dimension(1038, 532));
        getContentPane().setLayout(null);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setInheritsPopupMenu(true);
        Background.setMaximumSize(new java.awt.Dimension(1038, 532));
        Background.setMinimumSize(new java.awt.Dimension(1038, 532));
        Background.setName(""); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(1038, 532));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logobg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSena.png"))); // NOI18N
        Background.add(Logobg, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 300, 290));

        NombreAct.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        NombreAct.setForeground(new java.awt.Color(255, 255, 255));
        NombreAct.setText("GUI");
        Background.add(NombreAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, -1, -1));

        FondoBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.png"))); // NOI18N
        Background.add(FondoBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 0, 340, 530));

        jTextFieldUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldUsuario.setText("Ingrese su nombre");
        jTextFieldUsuario.setToolTipText("NOMBRE");
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        Background.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 600, 45));

        jPasswordFileClave.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPasswordFileClave.setText("Ingrese su contraseña");
        jPasswordFileClave.setBorder(null);
        Background.add(jPasswordFileClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 610, 45));

        jButtonIniciar.setBackground(new java.awt.Color(51, 255, 51));
        jButtonIniciar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonIniciar.setText("INICIAR SESION");
        jButtonIniciar.setBorder(null);
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        Background.add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 243, 53));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("INICIAR SESIÓN");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        Usuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Usuario.setText("USUARIO");
        Background.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        passUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        passUsuario.setText("CONTRASEÑA");
        Background.add(passUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        SeparadorUsuario.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(SeparadorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 610, 20));

        SeparadorPassword.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(SeparadorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 610, 40));

        getContentPane().add(Background);
        Background.setBounds(0, 0, 1038, 532);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        if (jTextFieldUsuario.getText().equals("James") && jPasswordFileClave.getText().equals("123")){
            JOptionPane.showMessageDialog(null, "Bienvenido!");
            Menu menu = new Menu();
            menu.setVisible(true);
            dispose();
        }else{
        JOptionPane.showMessageDialog(null, "Error, revisar datos de inicio de sesion");
        }
    
        
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel FondoBg;
    private javax.swing.JLabel Logobg;
    private javax.swing.JLabel NombreAct;
    private javax.swing.JSeparator SeparadorPassword;
    private javax.swing.JSeparator SeparadorUsuario;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordFileClave;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel passUsuario;
    // End of variables declaration//GEN-END:variables
}
