/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author SENA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAprendiz = new javax.swing.JButton();
        jButtonCirculo = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonCirculo1 = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        Color = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        Color2 = new javax.swing.JPanel();
        jButtonVideoJuego = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 660));
        setMinimumSize(new java.awt.Dimension(600, 660));
        getContentPane().setLayout(null);

        jButtonAprendiz.setBackground(new java.awt.Color(153, 255, 153));
        jButtonAprendiz.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jButtonAprendiz.setText("INGRESAR APRENDIZ");
        jButtonAprendiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAprendizActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAprendiz);
        jButtonAprendiz.setBounds(60, 150, 484, 61);

        jButtonCirculo.setBackground(new java.awt.Color(255, 255, 102));
        jButtonCirculo.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jButtonCirculo.setText("AREA DE UN CIRCULO");
        jButtonCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCirculoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCirculo);
        jButtonCirculo.setBounds(60, 220, 484, 61);

        jButtonAtras.setBackground(new java.awt.Color(102, 255, 51));
        jButtonAtras.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jButtonAtras.setText("ATRAS");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras);
        jButtonAtras.setBounds(0, 0, 170, 40);

        jButtonCirculo1.setBackground(new java.awt.Color(153, 204, 255));
        jButtonCirculo1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jButtonCirculo1.setText("OPERACIONES BÁSICAS");
        jButtonCirculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCirculo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCirculo1);
        jButtonCirculo1.setBounds(40, 290, 520, 61);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(null);

        Color.setBackground(new java.awt.Color(255, 153, 51));

        jLabelMenu.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelMenu.setText("MENU");
        Color.add(jLabelMenu);

        bg.add(Color);
        Color.setBounds(0, 60, 600, 70);

        Color2.setBackground(new java.awt.Color(153, 153, 255));
        Color2.setLayout(null);

        jButtonVideoJuego.setBackground(new java.awt.Color(255, 51, 51));
        jButtonVideoJuego.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jButtonVideoJuego.setText("VIDEOJUEGOS");
        jButtonVideoJuego.setMaximumSize(new java.awt.Dimension(515, 61));
        jButtonVideoJuego.setMinimumSize(new java.awt.Dimension(515, 61));
        jButtonVideoJuego.setPreferredSize(new java.awt.Dimension(515, 61));
        jButtonVideoJuego.setRolloverEnabled(false);
        jButtonVideoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVideoJuegoActionPerformed(evt);
            }
        });
        Color2.add(jButtonVideoJuego);
        jButtonVideoJuego.setBounds(140, 240, 330, 50);

        bg.add(Color2);
        Color2.setBounds(0, 130, 600, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Java.jpg"))); // NOI18N
        bg.add(jLabel2);
        jLabel2.setBounds(100, 450, 520, 190);

        getContentPane().add(bg);
        bg.setBounds(0, -10, 600, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAprendizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAprendizActionPerformed
            
        Aprendiz aprendiz = new Aprendiz();
        dispose();
            aprendiz.setVisible(true);    }//GEN-LAST:event_jButtonAprendizActionPerformed

    private void jButtonCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCirculoActionPerformed
        Circulo circulo = new Circulo();
        circulo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCirculoActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonCirculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCirculo1ActionPerformed
        Matematica matematica = new Matematica();
        matematica.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCirculo1ActionPerformed

    private void jButtonVideoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVideoJuegoActionPerformed
        VideoDeJuegos videodejuegos = new VideoDeJuegos();
        videodejuegos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVideoJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Color;
    private javax.swing.JPanel Color2;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButtonAprendiz;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonCirculo;
    private javax.swing.JButton jButtonCirculo1;
    private javax.swing.JButton jButtonVideoJuego;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMenu;
    // End of variables declaration//GEN-END:variables
}
